### ISSUE TITLE
suggestion: Is there any plan for support more platform? (Android)

### ISSUE THREAD

**Issue by jeonghyeon-net** [baekteun/GRIG-iOS#2]
iOS 이외의 플랫폼도 지원할 예정이 있을까요?

Example:

* Android
* MacOS
* Linux

**Comment by jeonghyeon-net** [comment]
https://gri-g.github.io/ 알고보니 웹이 이미 구현되어있었군요;;

웹만 있으면 모든 플랫폼에서 다 사용할 수 있으니까,

이 이슈는 닫겠습니다.

**Comment by baekteun** [comment]
> iOS 이외의 플랫폼도 지원할 예정이 있을까요?
> 
> Example:
> 
> * Android
> * MacOS
> * Linux
> 

안녕하세요! 우선 제가 iOS 이외의 플랫폼을 지원할 예정은 아직은 없습니다. 다만, GRIG의 API가 Open API이니 만큼 안드로이드 플랫폼도 자연스럽게 지원이 될거라 생각합니다.
또한 macOS 같은 경우 M1 이상을 탑재한 mac의 경우에는 지원되는 상태입니다. Intel mac도 지원하는 것에 관해서는 조금 고민이 필요할 것 같습니다.
관심 가져주신 것 감사합니다!
